// Code generated by protoc-gen-go. DO NOT EDIT.
// source: communication.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommunicateData_EDirection int32

const (
	CommunicateData_Send CommunicateData_EDirection = 0
	CommunicateData_Recv CommunicateData_EDirection = 1
)

var CommunicateData_EDirection_name = map[int32]string{
	0: "Send",
	1: "Recv",
}

var CommunicateData_EDirection_value = map[string]int32{
	"Send": 0,
	"Recv": 1,
}

func (x CommunicateData_EDirection) String() string {
	return proto.EnumName(CommunicateData_EDirection_name, int32(x))
}

func (CommunicateData_EDirection) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{0, 0}
}

type CommunicateData struct {
	Index                uint32                     `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Direction            CommunicateData_EDirection `protobuf:"varint,2,opt,name=direction,proto3,enum=types.CommunicateData_EDirection" json:"direction,omitempty"`
	TimePoint            int64                      `protobuf:"varint,3,opt,name=time_point,json=timePoint,proto3" json:"time_point,omitempty"`
	Data                 []byte                     `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *CommunicateData) Reset()         { *m = CommunicateData{} }
func (m *CommunicateData) String() string { return proto.CompactTextString(m) }
func (*CommunicateData) ProtoMessage()    {}
func (*CommunicateData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{0}
}

func (m *CommunicateData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunicateData.Unmarshal(m, b)
}
func (m *CommunicateData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunicateData.Marshal(b, m, deterministic)
}
func (m *CommunicateData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunicateData.Merge(m, src)
}
func (m *CommunicateData) XXX_Size() int {
	return xxx_messageInfo_CommunicateData.Size(m)
}
func (m *CommunicateData) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunicateData.DiscardUnknown(m)
}

var xxx_messageInfo_CommunicateData proto.InternalMessageInfo

func (m *CommunicateData) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *CommunicateData) GetDirection() CommunicateData_EDirection {
	if m != nil {
		return m.Direction
	}
	return CommunicateData_Send
}

func (m *CommunicateData) GetTimePoint() int64 {
	if m != nil {
		return m.TimePoint
	}
	return 0
}

func (m *CommunicateData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SummaryData struct {
	SendPacks            uint32             `protobuf:"varint,1,opt,name=send_packs,json=sendPacks,proto3" json:"send_packs,omitempty"`
	SendBytes            uint32             `protobuf:"varint,2,opt,name=send_bytes,json=sendBytes,proto3" json:"send_bytes,omitempty"`
	RecvPacks            uint32             `protobuf:"varint,3,opt,name=recv_packs,json=recvPacks,proto3" json:"recv_packs,omitempty"`
	RecvBytes            uint32             `protobuf:"varint,4,opt,name=recv_bytes,json=recvBytes,proto3" json:"recv_bytes,omitempty"`
	ErrorCount           uint32             `protobuf:"varint,5,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	QueueSize            uint32             `protobuf:"varint,6,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"`
	Buffer               []*CommunicateData `protobuf:"bytes,7,rep,name=buffer,proto3" json:"buffer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SummaryData) Reset()         { *m = SummaryData{} }
func (m *SummaryData) String() string { return proto.CompactTextString(m) }
func (*SummaryData) ProtoMessage()    {}
func (*SummaryData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{1}
}

func (m *SummaryData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummaryData.Unmarshal(m, b)
}
func (m *SummaryData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummaryData.Marshal(b, m, deterministic)
}
func (m *SummaryData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummaryData.Merge(m, src)
}
func (m *SummaryData) XXX_Size() int {
	return xxx_messageInfo_SummaryData.Size(m)
}
func (m *SummaryData) XXX_DiscardUnknown() {
	xxx_messageInfo_SummaryData.DiscardUnknown(m)
}

var xxx_messageInfo_SummaryData proto.InternalMessageInfo

func (m *SummaryData) GetSendPacks() uint32 {
	if m != nil {
		return m.SendPacks
	}
	return 0
}

func (m *SummaryData) GetSendBytes() uint32 {
	if m != nil {
		return m.SendBytes
	}
	return 0
}

func (m *SummaryData) GetRecvPacks() uint32 {
	if m != nil {
		return m.RecvPacks
	}
	return 0
}

func (m *SummaryData) GetRecvBytes() uint32 {
	if m != nil {
		return m.RecvBytes
	}
	return 0
}

func (m *SummaryData) GetErrorCount() uint32 {
	if m != nil {
		return m.ErrorCount
	}
	return 0
}

func (m *SummaryData) GetQueueSize() uint32 {
	if m != nil {
		return m.QueueSize
	}
	return 0
}

func (m *SummaryData) GetBuffer() []*CommunicateData {
	if m != nil {
		return m.Buffer
	}
	return nil
}

type IPCMessage struct {
	SeqNo                uint32   `protobuf:"varint,1,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`
	Identify             uint32   `protobuf:"varint,2,opt,name=identify,proto3" json:"identify,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IPCMessage) Reset()         { *m = IPCMessage{} }
func (m *IPCMessage) String() string { return proto.CompactTextString(m) }
func (*IPCMessage) ProtoMessage()    {}
func (*IPCMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b64068f22c460ac1, []int{2}
}

func (m *IPCMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IPCMessage.Unmarshal(m, b)
}
func (m *IPCMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IPCMessage.Marshal(b, m, deterministic)
}
func (m *IPCMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IPCMessage.Merge(m, src)
}
func (m *IPCMessage) XXX_Size() int {
	return xxx_messageInfo_IPCMessage.Size(m)
}
func (m *IPCMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_IPCMessage.DiscardUnknown(m)
}

var xxx_messageInfo_IPCMessage proto.InternalMessageInfo

func (m *IPCMessage) GetSeqNo() uint32 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *IPCMessage) GetIdentify() uint32 {
	if m != nil {
		return m.Identify
	}
	return 0
}

func (m *IPCMessage) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *IPCMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("types.CommunicateData_EDirection", CommunicateData_EDirection_name, CommunicateData_EDirection_value)
	proto.RegisterType((*CommunicateData)(nil), "types.CommunicateData")
	proto.RegisterType((*SummaryData)(nil), "types.SummaryData")
	proto.RegisterType((*IPCMessage)(nil), "types.IPCMessage")
}

func init() { proto.RegisterFile("communication.proto", fileDescriptor_b64068f22c460ac1) }

var fileDescriptor_b64068f22c460ac1 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcd, 0x8e, 0x9b, 0x30,
	0x10, 0xc7, 0xeb, 0x42, 0x68, 0x98, 0xf4, 0x23, 0x72, 0x3f, 0x84, 0x2a, 0x45, 0xa5, 0x9c, 0x38,
	0x71, 0x48, 0x1f, 0xa0, 0x52, 0x93, 0x1e, 0xf6, 0xb0, 0xab, 0x88, 0x3c, 0x00, 0x72, 0x60, 0xb2,
	0xb2, 0x76, 0xb1, 0x89, 0x6d, 0xa2, 0x25, 0xef, 0xb6, 0x0f, 0xb6, 0xb7, 0x95, 0x0d, 0x21, 0xd2,
	0x2a, 0x37, 0xcf, 0xef, 0xe7, 0xff, 0x88, 0x61, 0x0c, 0x5f, 0x4b, 0x59, 0xd7, 0xad, 0xe0, 0x25,
	0x33, 0x5c, 0x8a, 0xac, 0x51, 0xd2, 0x48, 0x3a, 0x31, 0x5d, 0x83, 0x3a, 0x79, 0x26, 0xf0, 0x65,
	0x35, 0x6a, 0x5c, 0x33, 0xc3, 0xe8, 0x37, 0x98, 0x70, 0x51, 0xe1, 0x53, 0x44, 0x62, 0x92, 0x7e,
	0xca, 0xfb, 0x82, 0xfe, 0x85, 0xb0, 0xe2, 0x0a, 0x4b, 0xdb, 0x23, 0x7a, 0x1f, 0x93, 0xf4, 0xf3,
	0xf2, 0x77, 0xe6, 0x9a, 0x64, 0x6f, 0x1a, 0x64, 0xff, 0xd7, 0xe7, 0x8b, 0xf9, 0x25, 0x43, 0x17,
	0x00, 0x86, 0xd7, 0x58, 0x34, 0x92, 0x0b, 0x13, 0x79, 0x31, 0x49, 0xbd, 0x3c, 0xb4, 0x64, 0x63,
	0x01, 0xa5, 0xe0, 0x57, 0xcc, 0xb0, 0xc8, 0x8f, 0x49, 0xfa, 0x31, 0x77, 0xe7, 0x24, 0x06, 0xb8,
	0xf4, 0xa2, 0x53, 0xf0, 0xb7, 0x28, 0xaa, 0xf9, 0x3b, 0x7b, 0xca, 0xb1, 0x3c, 0xce, 0x49, 0xf2,
	0x42, 0x60, 0xb6, 0x6d, 0xeb, 0x9a, 0xa9, 0xce, 0x7d, 0xfb, 0x02, 0x40, 0xa3, 0xa8, 0x8a, 0x86,
	0x95, 0x0f, 0x7a, 0x18, 0x20, 0xb4, 0x64, 0x63, 0xc1, 0xa8, 0x77, 0x9d, 0x41, 0xed, 0xa6, 0x18,
	0xf4, 0x3f, 0x0b, 0xac, 0x56, 0x58, 0x1e, 0x87, 0xb4, 0xd7, 0x6b, 0x4b, 0xc6, 0xb4, 0xd3, 0x7d,
	0xda, 0xbf, 0xe8, 0x3e, 0xfd, 0x0b, 0x66, 0xa8, 0x94, 0x54, 0x45, 0x29, 0x5b, 0x61, 0xa2, 0x89,
	0xf3, 0xe0, 0xd0, 0xca, 0x12, 0x9b, 0x3f, 0xb4, 0xd8, 0x62, 0xa1, 0xf9, 0x09, 0xa3, 0xa0, 0xcf,
	0x3b, 0xb2, 0xe5, 0x27, 0xa4, 0x19, 0x04, 0xbb, 0x76, 0xbf, 0x47, 0x15, 0x7d, 0x88, 0xbd, 0x74,
	0xb6, 0xfc, 0x71, 0xfd, 0xf7, 0xe6, 0xc3, 0xad, 0x84, 0x03, 0xdc, 0x6c, 0x56, 0xb7, 0xa8, 0x35,
	0xbb, 0x47, 0xfa, 0x1d, 0x02, 0x8d, 0x87, 0x42, 0xc8, 0xf3, 0xda, 0x34, 0x1e, 0xee, 0x24, 0xfd,
	0x09, 0x53, 0x5e, 0xa1, 0x30, 0x7c, 0xdf, 0x0d, 0xf3, 0x8e, 0xb5, 0x5d, 0xb4, 0xe1, 0xe6, 0x11,
	0xdd, 0xa4, 0x61, 0xde, 0x17, 0xd7, 0x16, 0xb1, 0x0b, 0xdc, 0xa3, 0xf9, 0xf3, 0x1a, 0x00, 0x00,
	0xff, 0xff, 0x81, 0xc9, 0xac, 0x54, 0x4b, 0x02, 0x00, 0x00,
}
