// Code generated by protoc-gen-go. DO NOT EDIT.
// source: global.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AlarmState int32

const (
	AlarmState_Overflow       AlarmState = 0
	AlarmState_Underflow      AlarmState = 1
	AlarmState_AutoCanceled   AlarmState = 2
	AlarmState_ManualCanceled AlarmState = 3
)

var AlarmState_name = map[int32]string{
	0: "Overflow",
	1: "Underflow",
	2: "AutoCanceled",
	3: "ManualCanceled",
}

var AlarmState_value = map[string]int32{
	"Overflow":       0,
	"Underflow":      1,
	"AutoCanceled":   2,
	"ManualCanceled": 3,
}

func (x AlarmState) String() string {
	return proto.EnumName(AlarmState_name, int32(x))
}

func (AlarmState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4baa8fc7dedf329e, []int{0}
}

type WSNumber struct {
	Value                float64  `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WSNumber) Reset()         { *m = WSNumber{} }
func (m *WSNumber) String() string { return proto.CompactTextString(m) }
func (*WSNumber) ProtoMessage()    {}
func (*WSNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_4baa8fc7dedf329e, []int{0}
}

func (m *WSNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WSNumber.Unmarshal(m, b)
}
func (m *WSNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WSNumber.Marshal(b, m, deterministic)
}
func (m *WSNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WSNumber.Merge(m, src)
}
func (m *WSNumber) XXX_Size() int {
	return xxx_messageInfo_WSNumber.Size(m)
}
func (m *WSNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_WSNumber.DiscardUnknown(m)
}

var xxx_messageInfo_WSNumber proto.InternalMessageInfo

func (m *WSNumber) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type WSData struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                *WSNumber `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	RangeLow             *WSNumber `protobuf:"bytes,4,opt,name=range_low,json=rangeLow,proto3" json:"range_low,omitempty"`
	RangeHigh            *WSNumber `protobuf:"bytes,5,opt,name=range_high,json=rangeHigh,proto3" json:"range_high,omitempty"`
	WarningLow           *WSNumber `protobuf:"bytes,6,opt,name=warning_low,json=warningLow,proto3" json:"warning_low,omitempty"`
	WarningHigh          *WSNumber `protobuf:"bytes,7,opt,name=warning_high,json=warningHigh,proto3" json:"warning_high,omitempty"`
	WarningIgnoreCount   uint32    `protobuf:"varint,8,opt,name=warning_ignore_count,json=warningIgnoreCount,proto3" json:"warning_ignore_count,omitempty"`
	ErrorLow             *WSNumber `protobuf:"bytes,9,opt,name=error_low,json=errorLow,proto3" json:"error_low,omitempty"`
	ErrorHigh            *WSNumber `protobuf:"bytes,10,opt,name=error_high,json=errorHigh,proto3" json:"error_high,omitempty"`
	ErrorIgnoreCount     uint32    `protobuf:"varint,11,opt,name=error_ignore_count,json=errorIgnoreCount,proto3" json:"error_ignore_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *WSData) Reset()         { *m = WSData{} }
func (m *WSData) String() string { return proto.CompactTextString(m) }
func (*WSData) ProtoMessage()    {}
func (*WSData) Descriptor() ([]byte, []int) {
	return fileDescriptor_4baa8fc7dedf329e, []int{1}
}

func (m *WSData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WSData.Unmarshal(m, b)
}
func (m *WSData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WSData.Marshal(b, m, deterministic)
}
func (m *WSData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WSData.Merge(m, src)
}
func (m *WSData) XXX_Size() int {
	return xxx_messageInfo_WSData.Size(m)
}
func (m *WSData) XXX_DiscardUnknown() {
	xxx_messageInfo_WSData.DiscardUnknown(m)
}

var xxx_messageInfo_WSData proto.InternalMessageInfo

func (m *WSData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WSData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *WSData) GetValue() *WSNumber {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *WSData) GetRangeLow() *WSNumber {
	if m != nil {
		return m.RangeLow
	}
	return nil
}

func (m *WSData) GetRangeHigh() *WSNumber {
	if m != nil {
		return m.RangeHigh
	}
	return nil
}

func (m *WSData) GetWarningLow() *WSNumber {
	if m != nil {
		return m.WarningLow
	}
	return nil
}

func (m *WSData) GetWarningHigh() *WSNumber {
	if m != nil {
		return m.WarningHigh
	}
	return nil
}

func (m *WSData) GetWarningIgnoreCount() uint32 {
	if m != nil {
		return m.WarningIgnoreCount
	}
	return 0
}

func (m *WSData) GetErrorLow() *WSNumber {
	if m != nil {
		return m.ErrorLow
	}
	return nil
}

func (m *WSData) GetErrorHigh() *WSNumber {
	if m != nil {
		return m.ErrorHigh
	}
	return nil
}

func (m *WSData) GetErrorIgnoreCount() uint32 {
	if m != nil {
		return m.ErrorIgnoreCount
	}
	return 0
}

type SAlarmInfo struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	State                AlarmState `protobuf:"varint,2,opt,name=state,proto3,enum=types.AlarmState" json:"state,omitempty"`
	Value                *WSNumber  `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Bound                *WSNumber  `protobuf:"bytes,4,opt,name=bound,proto3" json:"bound,omitempty"`
	Time                 int64      `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SAlarmInfo) Reset()         { *m = SAlarmInfo{} }
func (m *SAlarmInfo) String() string { return proto.CompactTextString(m) }
func (*SAlarmInfo) ProtoMessage()    {}
func (*SAlarmInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4baa8fc7dedf329e, []int{2}
}

func (m *SAlarmInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SAlarmInfo.Unmarshal(m, b)
}
func (m *SAlarmInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SAlarmInfo.Marshal(b, m, deterministic)
}
func (m *SAlarmInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SAlarmInfo.Merge(m, src)
}
func (m *SAlarmInfo) XXX_Size() int {
	return xxx_messageInfo_SAlarmInfo.Size(m)
}
func (m *SAlarmInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SAlarmInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SAlarmInfo proto.InternalMessageInfo

func (m *SAlarmInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SAlarmInfo) GetState() AlarmState {
	if m != nil {
		return m.State
	}
	return AlarmState_Overflow
}

func (m *SAlarmInfo) GetValue() *WSNumber {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *SAlarmInfo) GetBound() *WSNumber {
	if m != nil {
		return m.Bound
	}
	return nil
}

func (m *SAlarmInfo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type WSByteArray struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WSByteArray) Reset()         { *m = WSByteArray{} }
func (m *WSByteArray) String() string { return proto.CompactTextString(m) }
func (*WSByteArray) ProtoMessage()    {}
func (*WSByteArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_4baa8fc7dedf329e, []int{3}
}

func (m *WSByteArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WSByteArray.Unmarshal(m, b)
}
func (m *WSByteArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WSByteArray.Marshal(b, m, deterministic)
}
func (m *WSByteArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WSByteArray.Merge(m, src)
}
func (m *WSByteArray) XXX_Size() int {
	return xxx_messageInfo_WSByteArray.Size(m)
}
func (m *WSByteArray) XXX_DiscardUnknown() {
	xxx_messageInfo_WSByteArray.DiscardUnknown(m)
}

var xxx_messageInfo_WSByteArray proto.InternalMessageInfo

func (m *WSByteArray) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type RedisMessage struct {
	From                 string       `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string       `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Data                 *WSByteArray `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *RedisMessage) Reset()         { *m = RedisMessage{} }
func (m *RedisMessage) String() string { return proto.CompactTextString(m) }
func (*RedisMessage) ProtoMessage()    {}
func (*RedisMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_4baa8fc7dedf329e, []int{4}
}

func (m *RedisMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedisMessage.Unmarshal(m, b)
}
func (m *RedisMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedisMessage.Marshal(b, m, deterministic)
}
func (m *RedisMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedisMessage.Merge(m, src)
}
func (m *RedisMessage) XXX_Size() int {
	return xxx_messageInfo_RedisMessage.Size(m)
}
func (m *RedisMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_RedisMessage.DiscardUnknown(m)
}

var xxx_messageInfo_RedisMessage proto.InternalMessageInfo

func (m *RedisMessage) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *RedisMessage) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *RedisMessage) GetData() *WSByteArray {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("types.AlarmState", AlarmState_name, AlarmState_value)
	proto.RegisterType((*WSNumber)(nil), "types.WSNumber")
	proto.RegisterType((*WSData)(nil), "types.WSData")
	proto.RegisterType((*SAlarmInfo)(nil), "types.SAlarmInfo")
	proto.RegisterType((*WSByteArray)(nil), "types.WSByteArray")
	proto.RegisterType((*RedisMessage)(nil), "types.RedisMessage")
}

func init() { proto.RegisterFile("global.proto", fileDescriptor_4baa8fc7dedf329e) }

var fileDescriptor_4baa8fc7dedf329e = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x6a, 0xdb, 0x40,
	0x10, 0xae, 0xe4, 0xc8, 0xb5, 0xc7, 0x8a, 0xeb, 0x0e, 0x39, 0xe8, 0xe8, 0x0a, 0xd2, 0x9a, 0x12,
	0x4c, 0x71, 0x9f, 0xc0, 0x4d, 0x0f, 0x0d, 0x34, 0x0d, 0x48, 0x14, 0x43, 0x2f, 0x61, 0x1c, 0xad,
	0x65, 0x81, 0xb4, 0x1b, 0x56, 0xab, 0x18, 0x3f, 0x51, 0x9f, 0xa8, 0xef, 0x53, 0x34, 0xbb, 0x72,
	0x5b, 0x6a, 0x43, 0x6e, 0x23, 0x7d, 0xdf, 0x7c, 0x3f, 0x8c, 0x04, 0x61, 0x5e, 0xaa, 0x35, 0x95,
	0xf3, 0x47, 0xad, 0x8c, 0xc2, 0xc0, 0xec, 0x1f, 0x45, 0x1d, 0x4f, 0x61, 0xb0, 0x4a, 0xbf, 0x35,
	0xd5, 0x5a, 0x68, 0xbc, 0x80, 0xe0, 0x89, 0xca, 0x46, 0x44, 0xde, 0xd4, 0x9b, 0x79, 0x89, 0x7d,
	0x88, 0x7f, 0xf5, 0xa0, 0xbf, 0x4a, 0x3f, 0x93, 0x21, 0x1c, 0x83, 0x5f, 0x64, 0x8c, 0x0e, 0x13,
	0xbf, 0xc8, 0x10, 0xe1, 0x4c, 0x52, 0x25, 0x22, 0x9f, 0xdf, 0xf0, 0x8c, 0x97, 0x9d, 0x48, 0x6f,
	0xea, 0xcd, 0x46, 0x8b, 0x57, 0x73, 0xf6, 0x99, 0x77, 0x26, 0x4e, 0x15, 0xaf, 0x60, 0xa8, 0x49,
	0xe6, 0xe2, 0xbe, 0x54, 0xbb, 0xe8, 0xec, 0x38, 0x75, 0xc0, 0x8c, 0xaf, 0x6a, 0x87, 0x73, 0x00,
	0xcb, 0xde, 0x16, 0xf9, 0x36, 0x0a, 0x8e, 0xd3, 0xad, 0xe0, 0x97, 0x22, 0xdf, 0xe2, 0x07, 0x18,
	0xed, 0x48, 0xcb, 0x42, 0xe6, 0xac, 0xdf, 0x3f, 0xbe, 0x00, 0x8e, 0xd3, 0x3a, 0x2c, 0x20, 0xec,
	0x36, 0xd8, 0xe3, 0xe5, 0xf1, 0x95, 0x4e, 0xd6, 0xb9, 0x5c, 0x74, 0x3b, 0x45, 0x2e, 0x95, 0x16,
	0xf7, 0x0f, 0xaa, 0x91, 0x26, 0x1a, 0x4c, 0xbd, 0xd9, 0x79, 0x82, 0x0e, 0xbb, 0x61, 0xe8, 0xba,
	0x45, 0xda, 0xd6, 0x42, 0x6b, 0xa5, 0x39, 0xd5, 0xf0, 0x44, 0x6b, 0x66, 0xb8, 0xd6, 0x96, 0xcd,
	0x89, 0xe0, 0x44, 0x6b, 0xa6, 0x70, 0x9e, 0x2b, 0x40, 0xcb, 0xff, 0x27, 0xcd, 0x88, 0xd3, 0x4c,
	0x18, 0xf9, 0x2b, 0x4b, 0xfc, 0xd3, 0x03, 0x48, 0x97, 0x25, 0xe9, 0xea, 0x46, 0x6e, 0xd4, 0x7f,
	0xb7, 0x7d, 0x07, 0x41, 0x6d, 0xc8, 0xd8, 0xe3, 0x8e, 0x17, 0xaf, 0x9d, 0x2f, 0x2f, 0xa4, 0x2d,
	0x90, 0x58, 0xfc, 0xb9, 0x07, 0xbf, 0x84, 0x60, 0xad, 0x1a, 0x99, 0x9d, 0x3a, 0xb6, 0x45, 0xdb,
	0x4f, 0xca, 0x14, 0x95, 0xe0, 0x1b, 0xf7, 0x12, 0x9e, 0xe3, 0x37, 0x30, 0x5a, 0xa5, 0x9f, 0xf6,
	0x46, 0x2c, 0xb5, 0xa6, 0x7d, 0x4b, 0xc9, 0xc8, 0x10, 0x67, 0x0d, 0x13, 0x9e, 0xe3, 0x1f, 0x10,
	0x26, 0x22, 0x2b, 0xea, 0x5b, 0x51, 0xd7, 0x94, 0x8b, 0x96, 0xb3, 0xd1, 0xaa, 0x72, 0x7d, 0x78,
	0x6e, 0x1b, 0x1a, 0xe5, 0xbe, 0x55, 0xdf, 0x28, 0x7c, 0xeb, 0x74, 0x6c, 0x6e, 0x3c, 0x04, 0x3a,
	0x38, 0x59, 0xed, 0xf7, 0x77, 0x00, 0x7f, 0x5a, 0x63, 0x08, 0x83, 0xbb, 0x27, 0xa1, 0x37, 0xa5,
	0xda, 0x4d, 0x5e, 0xe0, 0x39, 0x0c, 0xbf, 0xcb, 0xcc, 0x3d, 0x7a, 0x38, 0x81, 0x70, 0xd9, 0x18,
	0x75, 0x4d, 0xf2, 0x41, 0x94, 0x22, 0x9b, 0xf8, 0x88, 0x30, 0xbe, 0x25, 0xd9, 0x50, 0x79, 0x78,
	0xd7, 0x5b, 0xf7, 0xf9, 0x0f, 0xfc, 0xf8, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x47, 0x16, 0x99, 0x27,
	0x91, 0x03, 0x00, 0x00,
}
